apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourism-deployment
  labels:
    app: tourism-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tourism-app
  template:
    metadata:
      labels:
        app: tourism-app
    spec:
      imagePullSecrets:
      - name: ecr-regcred
      containers:
      - name: tourism-container
        image: 873727239305.dkr.ecr.ap-southeast-2.amazonaws.com/tourism-app:latest
        ports:
        - containerPort: 80
